#ifndef MODEM_HTTP_H
#define MODEM_HTTP_H

/**
 * @file modem_http.h
 * @brief Modem HTTP/HTTPS interface API
 *
 * @details
 * This module provides an interface for performing HTTP and HTTPS
 * operations using a modem. It includes initialization, request handling,
 * data processing, and event notification mechanisms.
 *
 * The API is intended for embedded systems where communication is
 * performed via modem-based transport layers (e.g., UART).
 */

#include <stdint.h>
#include <stdbool.h>

/**
 * @brief HTTP(S) operation status and error codes
 *
 * @details
 * This enumeration defines all possible return codes generated by the
 * HTTP/HTTPS module. A value of @ref HTTP_ERR_OK indicates successful
 * execution, while all other values indicate specific failure conditions.
 *
 * These codes help in identifying failures related to network,
 * protocol handling, memory, or modem communication.
 */
typedef enum
{
    HTTP_ERR_OK = 0, /**< Operation completed successfully */

    HTTP_ERR_UNKNOWN = 701,    /**< Unknown or unspecified HTTP(S) error */
    HTTP_ERR_TIMEOUT = 702,    /**< HTTP(S) operation timed out */
    HTTP_ERR_BUSY = 703,       /**< HTTP(S) module is currently busy */
    HTTP_ERR_UART_BUSY = 704,  /**< Underlying UART interface is busy */
    HTTP_ERR_NO_REQUEST = 705, /**< No HTTP request has been initiated */

    HTTP_ERR_NETWORK_BUSY = 706,        /**< Network stack is busy */
    HTTP_ERR_NETWORK_OPEN_FAILED = 707, /**< Failed to establish network connection */
    HTTP_ERR_NETWORK_NO_CONFIG = 708,   /**< Network configuration is missing */
    HTTP_ERR_NETWORK_DEACTIVATED = 709, /**< Network context is deactivated */
    HTTP_ERR_NETWORK_ERROR = 710,       /**< General network-related error */

    HTTP_ERR_URL_ERROR = 711,        /**< Malformed or invalid URL */
    HTTP_ERR_EMPTY_URL = 712,        /**< URL string is empty */
    HTTP_ERR_IP_ADDRESS_ERROR = 713, /**< Invalid or unsupported IP address */
    HTTP_ERR_DNS_ERROR = 714,        /**< DNS resolution failed */

    HTTP_ERR_SOCKET_CREATE_ERROR = 715,  /**< Failed to create socket */
    HTTP_ERR_SOCKET_CONNECT_ERROR = 716, /**< Socket connection failed */
    HTTP_ERR_SOCKET_READ_ERROR = 717,    /**< Socket read operation failed */
    HTTP_ERR_SOCKET_WRITE_ERROR = 718,   /**< Socket write operation failed */
    HTTP_ERR_SOCKET_CLOSED = 719,        /**< Socket closed unexpectedly */

    HTTP_ERR_DATA_ENCODE_ERROR = 720, /**< Failed to encode request data */
    HTTP_ERR_DATA_DECODE_ERROR = 721, /**< Failed to decode response data */

    HTTP_ERR_READ_TIMEOUT = 722,    /**< Timeout occurred during read operation */
    HTTP_ERR_RESPONSE_FAILED = 723, /**< Invalid or unsuccessful HTTP(S) response */

    HTTP_ERR_INCOMING_CALL_BUSY = 724, /**< Operation interrupted by incoming call */
    HTTP_ERR_VOICE_CALL_BUSY = 725,    /**< Operation blocked due to active voice call */

    HTTP_ERR_INPUT_TIMEOUT = 726,         /**< Timeout while waiting for input */
    HTTP_ERR_WAIT_DATA_TIMEOUT = 727,     /**< Timeout while waiting for incoming data */
    HTTP_ERR_WAIT_RESPONSE_TIMEOUT = 728, /**< Timeout while waiting for HTTP(S) response */

    HTTP_ERR_MEMORY_ALLOCATION_FAILED = 729, /**< Memory allocation failure */
    HTTP_ERR_INVALID_PARAMETER = 730,        /**< Invalid input parameter */
    HTTP_ERR_WOULDBLOCK = 731,               /**< Operation would block in current state */
    HTTP_ERR_SSL_HANDSHAKE_FAILED = 732      /**< SSL/TLS handshake failure */

} http_err_code_t;

/**
 * @brief HTTP/HTTPS payload buffer descriptor
 *
 * @details
 * This structure represents a data buffer used for transmitting HTTP
 * request payloads or receiving HTTP response data.
 *
 * The buffer is not owned by the module unless explicitly documented.
 */
typedef struct
{
    char *data;      /**< Pointer to payload data buffer */
    size_t data_len; /**< Length of payload data in bytes */
} modem_http_payload_t;

/**
 * @brief HTTP/HTTPS event types
 *
 * @details
 * This enumeration defines the set of events generated by the HTTP/HTTPS
 * client during the lifecycle of a request. These events are delivered
 * to the registered callback function.
 */
typedef enum
{
    MODEM_HTTP_EVT_CONNECT = 0, /**< HTTP/HTTPS session successfully established */
    MODEM_HTTP_EVT_DISCONNECT,  /**< HTTP/HTTPS session terminated */
    MODEM_HTTP_EVT_DATA,        /**< Partial response data received */
    MODEM_HTTP_EVT_DATA_DONE,   /**< Complete response data received */
    MODEM_HTTP_EVT_ERROR        /**< Error occurred during operation */
} modem_http_event_t;

/**
 * @brief HTTP handler configuration structure
 *
 * @details
 * This structure holds configuration parameters required for initiating
 * an HTTP/HTTPS request.
 */
typedef struct
{
    const char *url; /**< Target URL for HTTP/HTTPS request */
} modem_http_handler_t;

/**
 * @brief HTTP callback function type
 *
 * @details
 * This callback is invoked by the HTTP module to notify the application
 * about events such as connection status, incoming data, or errors.
 *
 * @param event     Event type indicating the current state
 * @param msg       Optional message string (implementation-specific)
 * @param res_code  Result or error code (see @ref http_err_code_t)
 * @param payload   Pointer to associated payload data (if applicable)
 */
typedef void (*modem_http_cb_t)(
    modem_http_event_t event,
    const char *msg,
    int res_code,
    modem_http_payload_t *payload);

/* ============================= API Functions ============================= */

/**
 * @brief Initialize the modem HTTP service
 *
 * @details
 * Prepares the HTTP module for operation. This includes initializing
 * internal resources and preparing the modem interface.
 *
 * @retval true  Initialization successful
 * @retval false Initialization failed
 */
bool modem_http_init(void);

/**
 * @brief Perform an HTTP GET request
 *
 * @details
 * Initiates an HTTP GET request to the specified URL.
 *
 * @param url Pointer to null-terminated URL string
 *
 * @return Operation result (see @ref http_err_code_t)
 */
int modem_http_get(const char *url);

/**
 * @brief Register HTTP event callback
 *
 * @details
 * Registers a callback function to receive HTTP-related events.
 *
 * @param cb Pointer to callback function
 */
void modem_http_register_cb(modem_http_cb_t cb);

/**
 * @brief Process incoming HTTP data
 *
 * @details
 * Parses and processes raw data received from the modem interface.
 *
 * @param type Packet type identifier
 * @param data Pointer to raw data buffer
 */
void process_http_data(http_packet_type_t type, char *data);

/**
 * @brief Classify HTTP packet type
 *
 * @details
 * Determines the type of HTTP packet based on raw input data.
 *
 * @param data Pointer to raw data buffer
 *
 * @return Identified packet type
 */
http_packet_type_t http_classify_packet(const char *data);

// /**
//  * @brief Perform HTTP/HTTPS request
//  *
//  * @details
//  * Generic API for performing HTTP/HTTPS requests with custom parameters.
//  */
// bool modem_http_request(const modem_http_request_t *request,
//                         modem_http_response_t *response);

// /**
//  * @brief Deinitialize modem HTTP service
//  *
//  * @details
//  * Releases resources associated with the HTTP module.
//  */
// void modem_http_deinit(void);

#endif /* MODEM_HTTP_H */