#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "oal_timer.h"
#include "modem_datatypes.h"
#include "modem_http.h"

#include "esp_log.h"

/**
 * @brief Logging tag for HTTP example module
 */
#define TAG_HTTP "Modem HTTP Example"

/**
 * @brief HTTP event callback handler
 *
 * This function handles various HTTP events generated by the modem HTTP module.
 * It logs connection status, received data, completion, and error conditions.
 *
 * @param[in] event     HTTP event type
 * @param[in] msg       Optional message string (e.g., modem error description)
 * @param[in] res_code  HTTP response status code (e.g., 200, 404)
 * @param[in] payload   Pointer to HTTP payload structure (valid for DATA events)
 */
void http_event_handler(modem_http_event_t event, const char *msg, int res_code, modem_http_payload_t *payload)
{
    switch (event)
    {
    case MODEM_HTTP_EVT_CONNECT:
    {
        ESP_LOGI(TAG_HTTP, "CONNECT | Modem: %s | HTTP Status: %d", msg ? msg : "NULL", res_code);
        break;
    }

    case MODEM_HTTP_EVT_DISCONNECT:
    {
        ESP_LOGI(TAG_HTTP, "DISCONNECT");
        break;
    }

    case MODEM_HTTP_EVT_DATA:
    {
        if (payload && payload->data)
            ESP_LOGI(TAG_HTTP, "DATA (%d bytes):\n%s", payload->data_len, payload->data);
        else
            ESP_LOGW(TAG_HTTP, "DATA: NULL payload");
        break;
    }

    case MODEM_HTTP_EVT_DATA_DONE:
    {
        ESP_LOGI(TAG_HTTP, "COMPLETE | HTTP Status: %d", res_code);
        break;
    }

    case MODEM_HTTP_EVT_ERROR:
    {
        ESP_LOGE(TAG_HTTP, "ERROR | Modem: %s | HTTP Status: %d", msg ? msg : "UNKNOWN", res_code);
        break;
    }

    default:
    {
        ESP_LOGW(TAG_HTTP, "UNKNOWN EVENT");
        break;
    }
    }
}

/**
 * @brief Example function demonstrating modem HTTP usage
 *
 * This function initializes the modem HTTP module, registers the event callback,
 * and periodically performs HTTP GET requests to a test server.
 *
 * @note This function runs indefinitely in a loop.
 */
void modem_http_example(void)
{
    modem_http_register_cb(http_event_handler);
    modem_http_init();
    OAL_DelayMS(4);

    while (true)
    {
        modem_http_get("http://jsonplaceholder.typicode.com/posts");
        OAL_DelaySec(10);
    }
}